version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      
    depends_on:
      - nginx
  
  nginx:
    build: ./nginx
    
    volumes:
      - static_volume:/app/static
    
    ports:
      - 80:80

    depends_on:
      - web

  web:
    build:
      context: ./backend/app

    command: gunicorn --workers=3 backend.wsgi:application --bind 0.0.0.0:8000

    volumes:
      - static_volume:/app/static

    expose:
      - 8000

    env_file:
      - ./env/.env.prod
      
    depends_on:
      - db
  
  db:
    image: postgres:13.2-alpine

    volumes:
      - postgres_data:/var/lib/postgresql/data/

    env_file:
      - ./env/.env.prod

volumes:
  postgres_data:
  static_volume: